### ISSUE TITLE
Script error with TTT2

### ISSUE THREAD

**Issue by mexikoedi** [BadgerCode/tttdamagelogs#103]
I get the following error on the newest TTT2 version (0.13.0b).
```
[tttdamagelogs] addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:44: attempt to call method 'GetPlacer' (a nil value)
  1. Store - addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:44
   2. unknown - addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:30
    3. fn - addons/tttdamagelogs/lua/damagelogs/shared/events.lua:59
     4. Run - lua/ulib/shared/hook.lua:109
      5. GiveHealth - gamemodes/terrortown/entities/entities/ttt_health_station.lua:122
       6. unknown - gamemodes/terrortown/entities/entities/ttt_health_station.lua:162

[tttdamagelogs] addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:21: attempt to compare number with nil
  1. unknown - addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:21
  
Timer Failed! [HealTimer_STEAM_0:1:159775630][@addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua (line 18)]
```
This happens if someone places a health station and tries to use it.
It doesn't work and the console is getting spammed with these errors.

**Comment by BadgerCode** [comment]
Heyo!
Sorry for the delay.

The error comes from the damage logs code being unable to work out who placed the health station.
The code for handling players using the health station can be found here:
https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/shared/events/health.lua

<br>

In TTT, anytime someone uses a health station, it fires a `TTTPlayerUsedHealthStation` event.
The event contains the player using the health station, the health station entity & the amount of health the player gained.
https://github.com/Facepunch/garrysmod/blob/ea773354f1e402ea6a18c0a7daae52559c1206a5/garrysmod/gamemodes/terrortown/entities/entities/ttt_health_station.lua#L106
For some reason, in your case, the event is being fired without the health station entity.

<br>

Are you using any addons related to health stations?
Does this happen often? Or did it happen when a health station was destroyed?

**Comment by BadgerCode** [comment]
Yeah it looks like they've removed the "Placer" property of health stations, to determine who placed them.
So `GetPlacer` will no longer work for TTT2 and `GetOriginator` should be used instead
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/entities/ttt_base_placeable.lua#L41C35-L41C45

I believe this is the cause of the error, although the error does make it sound like the health station entity passed into the `TTTPlayerUsedHealthStation` hook is nil.
I shall do some tests


<br><br>

On top of this, the hook is now used to determine if the health station should work for the player
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/entities/entities/ttt_health_station.lua#L122-L124

Previously, the return value did not matter, so we will need to make sure that the hook doesn't stop health stations from healing.

**Comment by BadgerCode** [comment]
Ah yeah. That's the problem.

I've been able to reproduce it by replacing the vanilla TTT `Placer` property with TTT2's Originator property.

```
[tttdamagelogs] addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:44: attempt to call method 'GetPlacer' (a nil value)
  1. Store - addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:44
   2. unknown - addons/tttdamagelogs/lua/damagelogs/shared/events/health.lua:30
    3. fn - addons/tttdamagelogs/lua/damagelogs/shared/events.lua:59
     4. Run - addons/ulib/lua/ulib/shared/hook.lua:109
      5. GiveHealth - gamemodes/terrortown/entities/entities/ttt_health_station.lua:107
       6. unknown - gamemodes/terrortown/entities/entities/ttt_health_station.lua:135 (x28)
```

I shall look at creating a hotfix for this, to support both vanilla TTT and TTT2

**Comment by BadgerCode** [comment]
I have created a hotfix for this (see #104)

I've tested it with vanilla TTT and with some changes to the health station, to work more like the updated one in TTT2.
Could you possibly try using it?

I will release this tomorrow unless you find any issues

**Comment by mexikoedi** [comment]
Thank you for looking into it and for your thorough replies.

Indeed. GetOriginator is now being used.
There were a lot of under the hood changes in TTT2 recently.

I have looked though the PR and haven't seen anything wrong with it at first glance.

I can test it tomorrow and will post a comment here afterwards.

**Comment by mexikoedi** [comment]
I tested it and found no issues.
It seems to work accordingly and without creating any errors.
This issue seems to be fixed.

**Comment by BadgerCode** [comment]
Awesome! I shall release this as a patch now

**Comment by BadgerCode** [comment]
Released
https://github.com/BadgerCode/tttdamagelogs/releases/tag/v3.9.1
