### ISSUE TITLE
Simplified Chinese is garbled

### ISSUE THREAD

**Issue by sbzlzh** [BadgerCode/tttdamagelogs#112]
![QQ_1721809584320](https://github.com/user-attachments/assets/9224a9a9-09ff-4447-819c-477925802fe5)

**Comment by sbzlzh** [comment]
![QQ_1721809584320](https://github.com/user-attachments/assets/c2e27610-ce60-475b-82d8-8848efade851)

**Comment by BadgerCode** [comment]
Heyo!
Yeah unfortunately this is an issue that has been around for a while- #95 

I believe it's a problem with the database, but it has been sometime since I looked into it

**Comment by sbzlzh** [comment]
all right

**Comment by BadgerCode** [comment]
This will be fixed in the next release
