### ISSUE TITLE
A fresh install error

### ISSUE THREAD

**Issue by ihatemagic** [BadgerCode/tttdamagelogs#12]
[tttdamagelogs-3.3.0] addons/tttdamagelogs-3.3.0/lua/damagelogs/server/oldlogs.lua:192: bad argument #2 to 'format' (number expected, got string)
  1. format - [C]:-1
   2. fn - addons/tttdamagelogs-3.3.0/lua/damagelogs/server/oldlogs.lua:192
    3. Call - addons/flux/lua/ulib/shared/hook.lua:109
     4. EndRound - gamemodes/terrortown/gamemode/init.lua:770
      5. unknown - gamemodes/terrortown/gamemode/init.lua:322
 
It appears this issue is caused by this:
local newRowID = Damagelog.SQLiteDatabase.QueryValue("SELECT MAX(id)+1 FROM damagelog_oldlogs_v3")

and newRowID returns "NULL"

**Comment by BadgerCode** [comment]
Ah yeah. Good spot. I'll try get a hotfix out for this.

**Comment by BadgerCode** [comment]
Hey. I will release the fix for this now.

Sorry for the delay! I didn't have notifications turned on for this repository for some reason.
