### ISSUE TITLE
Kill credit issue

### ISSUE THREAD

**Issue by BadgerCode** [BadgerCode/tttdamagelogs#13]
![preview](https://media.discordapp.net/attachments/318595912941436930/789229526134685696/unknown.png)
Death scene:
https://cdn.discordapp.com/attachments/318595912941436930/789229865387294830/Bug.mp4

* `Snowy Time A` killed `example`
* The damage logs credit `TheGrinch_XaNKoN` with the kill

**Comment by BadgerCode** [comment]
These lines look kinda sus
https://github.com/BadgerCode/tttdamagelogs/blob/cedb1c0266144e4297c0fb92051d4e2017746b26/lua/damagelogs/shared/events/kills.lua#L12-L17

Seems that no matter how a player dies, if they were recently pushed, the player that pushed them gets blamed.

**Comment by Yogpod** [comment]
check if the person that pushed was holding the weapon the victim died from, if they weren't then credit the original attacker, or probably something along these lines would probably work

**Comment by BadgerCode** [comment]
So I tested a few scenarios and here's how it plays out:
```
When a player is shot
Attacker: Player [1][Badger].
Player that pushed: nil.
Damage info attacker: Player [1][Badger]


When a player is pushed, then shot by a different player
Attacker: Player [1][Badger].
Player that pushed: Player [4][Bot09].
Damage info attacker: Player [1][Badger]


When a player is pushed to their death
Attacker: Entity [0][worldspawn].
Player that pushed: Player [1][Badger].
Damage info attacker: Entity [0][worldspawn]
```

It seems that when someone is pushed to their death, it's the world that is considered the attacker.


I'm thinking of changing the push-kill detection to this:
```lua
local playerThatPushed = ply:GetPlayerThatRecentlyPushedMe()
if (playerThatPushed != nil and dmginfo:GetDamageType() == DMG_FALL and attacker:IsWorld()) then
    attacker = playerThatPushed
end
```

**Comment by BadgerCode** [comment]
This does mean that pushing someone into other hazards (e.g. fire, poison, physics) that causes their death won't be counted.

But it is very hard to know if the push did actually cause the player's death from fire/poison/physics/etc.
E.g. 
Player A pushes Player B
Player B then walks into fire/poison pit/spikes and dies

**Comment by BadgerCode** [comment]
If these other scenarios pose an issue, they can be discussed in a new issue.
