### ISSUE TITLE
SQLite error

### ISSUE THREAD

**Issue by ihatemagic** [BadgerCode/tttdamagelogs#16]
I have noticed that this particular error occurs numerous times per map. Although the directory is different, the lua files are the same except for the lua includes. It says there's an issue with autoslay line 47, but I can't figure out if this is a damagelog problem or maybe problem on my side.

[flux] addons/flux/lua/flux/modules/damagelogs/damagelogs/server/sqlite.lua:10: Error performing query UPDATE damagelog_nam...:
[SQL Error] near "LIMIT": syntax error
  1. assert - [C]:-1
   2. Query - addons/flux/lua/flux/modules/damagelogs/damagelogs/server/sqlite.lua:10
    3. fn - addons/flux/lua/flux/modules/damagelogs/damagelogs/server/autoslay.lua:47
     4. unknown - addons/flux/lua/ulib/shared/hook.lua:109
      5. UniqueID - [C]:-1
       6. echoToAdmins - addons/flux/lua/ulx/log.lua:164
        7. fn - addons/flux/lua/ulx/log.lua:202
         8. unknown - addons/flux/lua/ulib/shared/hook.lua:109

**Comment by BadgerCode** [comment]
Hey.
Was it a bot being slain?

If not, it might be to do with the player having strange letters in their name.
Could you share the name of the player or other players that were online at the time?

It seems this is the affected line
https://github.com/BadgerCode/tttdamagelogs/blob/4a0ca3f9fed53603556760ab59ef45f7be4a135a/lua/damagelogs/server/autoslay.lua#L47

**Comment by BadgerCode** [comment]
I believe that using `LIMIT` with an `UPDATE` query is not supported (at least some of the time) in Garry's Mod.

I've removed the usage of `LIMIT` as it's not really necessary anyway.

**Comment by BadgerCode** [comment]
This will be fixed in the next update (most likely v3.4.0).
There is still some more work to go into this update.

You can download the early version of this update from the [next-version branch here](https://github.com/BadgerCode/tttdamagelogs/archive/next-version.zip)
