### ISSUE TITLE
Update slays [BUG]

### ISSUE THREAD

**Issue by Flapchik** [BadgerCode/tttdamagelogs#24]
Leo_DiCaprio: !aslay H0ll0w 2
You added 2 autoslays to H0ll0w (#s)
addons/tttdamagelogs-master/lua/damagelogs/server/sqlite.lua:10: Error performing query UPDATE damagelog_aut...:
[SQL Error] near "LIMIT": syntax errorLeo_DiCaprio: !aslay H0ll0w 4
ServerLog: [ULX] Leo_DiCaprio removed the autoslays of H0ll0w.
Leo_DiCaprio: !aslay H0ll0w 0
You removed the autoslays of H0ll0w.
ServerLog: [ULX] Leo_DiCaprio added 1 autoslays to H0ll0w (#s)
Leo_DiCaprio: !aslay H0ll0w 1
You added 1 autoslays to H0ll0w (#s)
addons/tttdamagelogs-master/lua/damagelogs/server/sqlite.lua:10: Error performing query UPDATE damagelog_aut...:
[SQL Error] near "LIMIT": syntax errorLeo_DiCaprio: !aslay H0ll0w 2

**Comment by BadgerCode** [comment]
Hey. Thanks for raising this.

This sounds similar to #16 and should be fixed by #22

**Comment by BadgerCode** [comment]
This will be fixed in the next update (most likely v3.4.0).
There is still some more work to go into this update.

You can download the early version of this update from the [next-version branch here](https://github.com/BadgerCode/tttdamagelogs/archive/next-version.zip)
