### ISSUE TITLE
Too many symbols in report [BUG] and open Damage log chat (???)

### ISSUE THREAD

**Issue by Flapchik** [BadgerCode/tttdamagelogs#27]
[tttdamagelogs-master] Trying to send an overflowed net message!
  1. DoClick - addons/tttdamagelogs-master/lua/damagelogs/client/rdm_manager.lua:464
   2. unknown - lua/vgui/dlabel.lua:237

[Leo_DiCaprio|10|STEAM_0:0:25517972] Lua Error:

[tttdamagelogs-master] Trying to send an overflowed net message!
  1. DoClick - addons/tttdamagelogs-master/lua/damagelogs/client/rdm_manager.lua:464
   2. unknown - lua/vgui/dlabel.lua:237

[tttdamagelogs-master] Trying to send an overflowed net message!
  1. NewReport - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:109
   2. HandlePlayerReport - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:439
    3. func - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:508
     4. unknown - lua/includes/extensions/net.lua:32 (x2)

[tttdamagelogs-master] Trying to send an overflowed net message!
  1. UpdateReport - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:127
   2. HandlePlayerReport - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:491
    3. func - addons/tttdamagelogs-master/lua/damagelogs/server/rdm_manager.lua:508
     4. unknown - lua/includes/extensions/net.lua:32 (x2)

I submitted my report as a player, not as an administrator

https://user-images.githubusercontent.com/58729268/103439430-e437ff80-4c4d-11eb-846a-5a22be12abed.mov

**Comment by Flapchik** [comment]
When I reply to a report, the answer does not count.
https://user-images.githubusercontent.com/58729268/103439445-09c50900-4c4e-11eb-9569-d78a85d40790.mov

**Comment by BadgerCode** [comment]
Hey. Sorry I didn't notice this issue before.

Thanks for raising this! I will look into it.

**Comment by BadgerCode** [comment]
This should be fixed in the next release (pull request - #34)
Please comment if you still experience the issue after the update has been released

**Comment by BadgerCode** [comment]
Here's a preview.

The button shows "Your message is too long" when the report message is over 1000 characters

![image](https://user-images.githubusercontent.com/5206198/104363390-0282e280-550d-11eb-8cb0-ed94b14f6e51.png)
