### ISSUE TITLE
Previous Map reports are not working

### ISSUE THREAD

**Issue by SenseiHiraku** [BadgerCode/tttdamagelogs#32]
Hey there,
I´ve ran into an issue, that I had also on tommys old version and doesnt seem to be fixed now. (https://github.com/Tommy228/tttdamagelogs/issues/381)
When a staff member joins, and there are already created reports, it does not seem to be possible for him, to see them.
Same goes for the previous map reports with the difference, that all of them arent possible to be seen by the staff.

Something that I´ve also noticed after a mapchange, the damagelog from the last round of the previous map are also returning "empty protocol"

**Comment by BadgerCode** [comment]
Hey! Thanks for raising this.

Just to confirm, are you running your GMod server through a server provider/a dedicated server?
Or are you starting the server via the Garry's Mod main menu.

And do you have any screenshots of the "empty protocol" error?
Is it in console, or in the reports list?

**Comment by SenseiHiraku** [comment]
> Just to confirm, are you running your GMod server through a server provider/a dedicated server?
It´s a dedicated server, and we´re using damagelog with mysql connection (connection is working, I´ve checked this)
> And do you have any screenshots of the "empty protocol" error?
https://i.imgur.com/mhVo0BH.png (It´s in german, tho. Looked it up on the language file and it means "Emtpy Logs" in english, sorry for confusing)
One thing I´ve noticed now, when I click on a specific round of the current map, the damagelogs of this round are shown (tho I´ve joined serveral rounds later on a current map), that does only make problems on the "Last round of the previous map".

**Comment by Yogpod** [comment]
I had this problem, all i did was do 
`hook.Add("PlayerInitialSpawn", "SendReports", function(ply)
    timer.Simple(15,function()
        if IsValid(ply) then
        ply:UpdateReports()
         end
    end)
end)`
inside of rdm_manager, but this is probably a bandaid fix

**Comment by BadgerCode** [comment]
I have created a potential fix for this issue (#35).

Could you download it to see if it fixes the problem for you?

https://github.com/BadgerCode/tttdamagelogs/tree/Iss-32_previous_map_reports
1. Click the green "Code" button
2. Select "[Download Zip](https://github.com/BadgerCode/tttdamagelogs/archive/Iss-32_previous_map_reports.zip)"

**Comment by SenseiHiraku** [comment]
Hey there,
we´ve tested the changes for several days and it seems to fix the issue.
Thank you for that!

**Comment by BadgerCode** [comment]
Awesome! I'm glad to hear.

I will close this issue now.

Let me know if you have any other problems.
