### ISSUE TITLE
Slay message is missing admin name

### ISSUE THREAD

**Issue by BadgerCode** [BadgerCode/tttdamagelogs#41]
![image](https://user-images.githubusercontent.com/5206198/105888539-00d51680-6005-11eb-9e2e-519e4acf2483.png)

https://github.com/BadgerCode/tttdamagelogs/blob/b5fd4332e188b0ef1845c1458303c1638fff6994/lua/damagelogs/shared/autoslay.lua#L194-L195

This seems to have been a problem for quite some time.

**Comment by Yogpod** [comment]
probably due to https://github.com/BadgerCode/tttdamagelogs/blob/b5fd4332e188b0ef1845c1458303c1638fff6994/lua/damagelogs/server/autoslay.lua#L224

**Comment by BadgerCode** [comment]
Fixed in #63
