### ISSUE TITLE
No receiving function for 'DL_UpdateLogEnt'

### ISSUE THREAD

**Issue by Yogpod** [BadgerCode/tttdamagelogs#45]
it's added as a network string, & 'sent' twice in damagelogs\client\recording.lua, no idea what its purpose is or supposed to be since it also has no receiving function in tommy's repo.

**Comment by BadgerCode** [comment]
Huh. Weird.

It's probably safe to kill off the code to do with this network message.

**Comment by BadgerCode** [comment]
This has been fixed in #49 and will be included in the next release.
Thanks for raising this!
