### ISSUE TITLE
Bug with "Remove autoslay of The victim"

### ISSUE THREAD

**Issue by MetzyGG** [BadgerCode/tttdamagelogs#46]
Selecting "Remove autoslay of The victim" removes the aslay from the reported player and not from the victim
https://streamable.com/g27xt6

**Comment by BadgerCode** [comment]
Hey! Thanks for raising this.

Sorry it took so long to get back to you. I will look into this now to see if it's an easy fix.

**Comment by BadgerCode** [comment]
Hey. This has been fixed in #47 and will be included in the next update.
Thanks for raising this!
