### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MetzyGG** [BadgerCode/tttdamagelogs#52]
When a report is created, the "Canceled" tab already comes with an "X" icon (icon16/cross.png) and is only changed to a "Check" (icon16/tick.png) if the victim forgives the report, I believe that when a report is created and it hasn't been decided if it will be forgiven or continued, it should come with a different icon, something like "!" (icon16/exclamation.png), because the "X" can cause confusion with the staff handling the report if they miss the "Forgiven" and "Not Forgiven" notifications.

**Comment by BadgerCode** [comment]
Hey!

Yup I agree.
I think that makes sense.

**Comment by BadgerCode** [comment]
This will be added in the next version! Thanks for the suggestion!
