### ISSUE TITLE
Prevents "Custom Roles for TTT" from loading

### ISSUE THREAD

**Issue by squidserv** [BadgerCode/tttdamagelogs#55]
When installed on the server, this prevents https://steamcommunity.com/sharedfiles/filedetails/?id=2421039084 from loading at all. There aren't any lua errors it just stops it from running.

**Comment by BadgerCode** [comment]
Hey. Thanks for raising this!

This addon doesn't support any of the TTT-related addons which provide additional roles (e.g. TTT2).
I believe [some work was done to support custom roles](https://github.com/Tommy228/tttdamagelogs/pull/361), but I don't know how functional it is.

This is something I would like to add support for at some point.


Related issues:
https://github.com/Tommy228/tttdamagelogs/issues/372 TTT2 Bug Instead of an innocent, a traitor.
https://github.com/Tommy228/tttdamagelogs/issues/382 Supporting 'Custom Roles for TTT' addon

**Comment by squidserv** [comment]
So the OG damage logs on steam works with custom roles but doesn't show the custom role (defaulting to innocent). It requires mods to pay more attention but works. This one straight up breaks custom roles from loading somehow. It would be an easy fix to add the extra roles (we added a constant like TTT2) but I can't figure out what is stopping the roles from straight up loading

**Comment by BadgerCode** [comment]
Hm. There were some bug fixes made in this fork of the damage logs to do with displaying and recording roles.
I will have to test the damage logs with the custom roles addon to see what's going wrong.

**Comment by squidserv** [comment]
There unfortunately aren't any lua errors, or it would be easier to find. The old damage logs didn't work right when the source was loaded into the addons folder, so I'm gonna try testing to see if putting the workshop addon into my collection for this one makes a difference. Just waiting on anyone from my server to hop on to test

**Comment by squidserv** [comment]
Doesn't work installing from the workshop either

**Comment by squidserv** [comment]
I figured out what was breaking it btw, Damagelog.Autoslay_ForceRole = true in the config breaks the CR mod. I am submitting a few PRs, one to fix some Syntax errors, one to update TTT2 support, and one for CR support

**Comment by squidserv** [comment]
Wouldn't it make more sense to trigger ulx.forcenr rather than overriding the choose roles method in /server/autoslay.lua? That was what stops the CR from loading right. I can look into it later tonight for you as well. I also noticed I forgot to update a couple more ROLES constants to TTT2

**Comment by BadgerCode** [comment]
I'm not too familiar with the choose roles code in `lua/damagelogs/server/autoslay.lua`. I've not had to work on it so far.
When I look over the pull request I will take a look at this code.

**Comment by squidserv** [comment]
While I worked on that other commit last night, I (unsuccessfully) tried to implement using ulx.nextround() if either CR or TTT2 was installed. I need to do a bit more research into the method itself and how it's called and can try again on a future PR. As of right now, I updated it to ignore `Damagelog.Autoslay_ForceRole` if CR is installed, similar to how it did with TTT2 already

**Comment by BadgerCode** [comment]
Will be fixed in the next release!
