### ISSUE TITLE
Move addon configuration out of source control/lua files

### ISSUE THREAD

**Issue by BadgerCode** [BadgerCode/tttdamagelogs#60]
The configuration for this addon currently lives within `lua/damagelogs/config/config.lua`.

This causes 2 problems:
1. When updating their copy of the damage logs, server owners can accidentally overwrite their configuration changes with the latest copy of `lua/damagelogs/config/config.lua`
2. Server owners using the workshop version are unable to configure the addon

<br>

The configuration for this addon should:
* Live within a json file in the server's data folder
* Be configurable in-game via an admin-only section of the damage logs interface

**Comment by wgaylord** [comment]
I may begin to thinker with this in my free time.  Just to get some ideas flowing.

Would this be just an extra  config tab in the normal manager that is displayed for admins? (Or what ever group you want similar to the AddUser stuff in the current config. Like another bool that would say if you can see the config tab or not) 

Or maybe should it be a button (visible only to admins / group allowed to see it) that opens up its own menu with tabs? (Break it down into different groups like: permissions, autoslay , ban, and other options (for the ones that don't really group with the others)

**Comment by BadgerCode** [comment]
This was done in v3.6.0
