### ISSUE TITLE
3.4.0 damagelogs TTT2 ERROR KILL

### ISSUE THREAD

**Issue by dok441** [BadgerCode/tttdamagelogs#61]
Hello, in the new version, when a person is killed, an error pops up, and the corpse disappears.
TTT2 v0.9.2b used.

[tttdamagelogs-3.4.0] addons/tttdamagelogs-3.4.0/lua/damagelogs/shared/events/kills.lua:50: attempt to call method 'HasTeamRole' (a nil value)
  1. unknown - addons/tttdamagelogs-3.4.0/lua/damagelogs/shared/events/kills.lua:50
   2. func - addons/tttdamagelogs-3.4.0/lua/damagelogs/shared/events.lua:59
    3. unknown - lua/includes/modules/hook.lua:198
     4. FireBullets - [C]:-1
      5. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:582
       6. unknown - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:482

[ERROR] Warning! A net message (DL_Ded) is already started! Discarding in favor of the new message! (TTT2RemoveWeaponFromInventory)
  1. RemoveWeaponFromInventoryAndNotifyClient - gamemodes/terrortown/gamemode/server/sv_inventory.lua:36
   2. unknown - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:634
    3. FireBullets - [C]:-1
     4. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:582
      5. unknown - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:482

**Comment by BadgerCode** [comment]
Hey! Thanks for raising this.

I will look into this now.

**Comment by BadgerCode** [comment]
I have a fix in place for it.

I haven't played TTT2 much myself.
Do these log lines look correct?
Red = team damage
Black = enemy team damage

![image](https://user-images.githubusercontent.com/5206198/124658349-91a8fb80-de9b-11eb-9b7a-d92826af0854.png)

**Comment by BadgerCode** [comment]
I have released a hotfix for this
https://github.com/BadgerCode/tttdamagelogs/releases/tag/v3.4.1

The workshop version has been updated too.
Please let me know if you have any other problems!
