### ISSUE TITLE
Unable to view death scene for a report

### ISSUE THREAD

**Issue by BadgerCode** [BadgerCode/tttdamagelogs#68]
# Steps to reproduce
1. Have a report in the RDM manager
2. Right click on the report and click view death scene

# Expected result
* Death scene is shown

# Actual result
* Death scene is not shown
![result](https://cdn.discordapp.com/attachments/318595912941436930/932401558468063302/unknown.png)

# Notes
* Right clicking on a death log in the damage logs to view a death scene works
* Unclear if there are any errors
* This apparently always happens

**Comment by callumok2004** [comment]
The option is shown when you right-click a report.

View Death Scene works when you right-click a log for a death directly.

**Comment by BadgerCode** [comment]
Cheers! I have updated the issue
