### ISSUE TITLE
change keybind?

### ISSUE THREAD

**Issue by riot33k** [BadgerCode/tttdamagelogs#84]
im not sure how to change keybind and everytime i want to to open the damage logs it interferes with my clipping software

**Comment by BadgerCode** [comment]
Heyo!

You have two options:
- Bind a key to the command `damagelog` (just you can use this)
- Change the key used to open the damage log in the [server config](https://github.com/BadgerCode/tttdamagelogs/wiki/Configuring-the-damage-logs) (everyone in the server can use this)

**Comment by riot33k** [comment]
okay i got it to work now, thank you! i just didnt know what the command for the damagelogs in the console was.
