### ISSUE TITLE
Roles can't access rdm manager

### ISSUE THREAD

**Issue by Gnampfhurz** [BadgerCode/tttdamagelogs#88]
I've attached the content of my config.json as a txt file.
My problem is that the roles jr.operator, operator and moderator can't access the rdm manager while the permission is set to true.

{
	"Reports": {
		"MoreReportsPerRound": false,
		"ReportsBeforePlaying": false,
		"NoStaffReports": true
	},
	"DiscordWebhookMode": 2.0,
	"PrivateMessagePrefix": "[RDM Manager]",
	"AbuseMessageMode": 0.0,
	"ForcedLanguage": "",
	"RDM_Manager_Enabled": true,
	"HideDonateButton": false,
	"Autoslay": {
		"Autoslay_CheckCustom": false,
		"DefaultReason11": "Trolling",
		"DefaultReason9": "Prop kill",
		"DefaultReason3": "2x RDM",
		"DefaultReason5": "Mass RDM",
		"DefaultReason6": "Super Mass",
		"ShowRemainingSlays": false,
		"DefaultReason10": "Consistent RDM",
		"DefaultReason8": "Hacking",
		"DefaultReason1": "Random Damage",
		"DefaultReason2": "RDM",
		"DefaultReason12": "Minge",
		"ULX_Autoslay_ForceRole": true,
		"DefaultReason": "Breaking Rules",
		"DefaultReason4": "Attempted Mass",
		"DefaultReason7": "Ghosting",
		"ULX_AutoslayMode": 1.0
	},
	"Use_MySQL": false,
	"LogDays": 61.0,
	"UseWorkshop": true,
	"Commands": {
		"RDM_Manager_Command": "!report",
		"Respond_Command": "!respond"
	},
	"Key": 99.0,
	"Permissions": {
		"founder": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"jr.operator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		},
		"superadmin": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"owner": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"admin": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"user": {
			"access_level": 2.0,
			"can_access_rdm_manager": false
		},
		"admini": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"moderator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		},
		"operator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		}
	},
	"Ban": {
		"DefaultReason6": "Super Mass",
		"DefaultReason7": "Ghosting",
		"DefaultReason8": "Hacking",
		"DefaultReason11": "Random Damage",
		"DefaultReason1": "Random Damage and leave",
		"AllowBanningThruManager": true,
		"DefaultReason2": "RDM and leave",
		"DefaultReason12": "Trolling",
		"DefaultReason3": "2x RDM and leave",
		"DefaultReason10": "Attempted RDM",
		"DefaultReason4": "Attempted Mass and leave",
		"DefaultReason9": "Consistent RDM",
		"DefaultReason5": "Mass RDM"
	}
}

[config.txt](https://github.com/BadgerCode/tttdamagelogs/files/11940725/config.txt)

**Comment by BadgerCode** [comment]
Heyo!

Sorry for the delay. It's been a busy few days for me.

Regarding role permissions, this is the important part of the config
https://github.com/BadgerCode/tttdamagelogs/wiki/Configuring-the-damage-logs#permission-settings
```json
{
    "founder": {
        "access_level": 4.0,
        "can_access_rdm_manager": true
    },
    "jr.operator": {
        "access_level": 3.0,
        "can_access_rdm_manager": true
    },
    "superadmin": {
        "access_level": 4.0,
        "can_access_rdm_manager": true
    },
    "owner": {
        "access_level": 4.0,
        "can_access_rdm_manager": true
    },
    "admin": {
        "access_level": 4.0,
        "can_access_rdm_manager": true
    },
    "user": {
        "access_level": 2.0,
        "can_access_rdm_manager": false
    },
    "admini": {
        "access_level": 4.0,
        "can_access_rdm_manager": true
    },
    "moderator": {
        "access_level": 3.0,
        "can_access_rdm_manager": true
    },
    "operator": {
        "access_level": 3.0,
        "can_access_rdm_manager": true
    }
}
```

It looks correct.
You've got a number of staff roles that can access the RDM manager side of the interface.
Some staff can see the logs of the current round when alive.
Users can't access the RDM manager and can never see the logs of the current round.


A few questions

* Are you able to open up the damage logs in-game?
* Can anyone access the RDM manager?
* Are you sure that the role names are correct?

**Comment by Gnampfhurz** [comment]
Thanks for the answer and no worries about the delay :D

The access levels are as intended. All roles are able to open the damage logs in-game. 
Admins and Superadmins can access the RDM Manager. Although it is a clone of Admin, Admini can't access the RDM Manager.
I checked multiple times if the spelling is correct and it should be. Especially since "operator" is a standard ulx role.

**Comment by BadgerCode** [comment]
Hey @Gnampfhurz !
Sorry I've been a bit busy.

Are you still having problems with this?

**Comment by Gnampfhurz** [comment]
Nothing to be sorry for. I appreciate the answer. :)

The problem still persists, but I worked around it using the old config.lua.
After inserting and modifying the lua-file everything works as intended.

**Comment by BadgerCode** [comment]
Ah ok.
Glad to hear you found a workaround!

In your case, it was just these roles that couldn't access the RDM manager (but should be able to)
- jr.operator
- operator
- moderator

All of the other admin roles above could access the RDM manager?

**Comment by plally** [comment]
I have this issue with all roles excluding superadmin, after a little bit of investigation it seem like the permissions are correct serverside but not clientside so the RDM manager panel isnt being added.

Serverside
```
> ply:CanUseRDMManager() 
true

> Damagelog.User_rights["moderator"]
4
```
Clientside
```
> LocalPlayer():CanUseRDMManager()
false

> Damagelog.User_rights["moderator"]
nil
```

**Comment by wgaylord** [comment]
Hm, I bet we need to sync the config over to the client now. (Like use lua to sync it) since the client side won't get the roles by downloading the lua anymore.
